# Generated by Django 4.1 on 2022-09-02 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("task", "0002_remove_subtask_task_task_subtask"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="content",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="task",
            name="deadline",
        ),
        migrations.AddField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
