# Generated by Django 4.1 on 2022-09-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_rename_content_task_name_remove_task_deadline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="name",
        ),
        migrations.AddField(
            model_name="task",
            name="task_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
