# Generated by Django 4.1 on 2022-09-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_remove_task_name_task_task_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subtask",
            old_name="content",
            new_name="subtask_name",
        ),
    ]
